/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Datastore } from "./Datastore";
export type { LeagueRewards } from "./LeagueRewards";
export type { LeagueX3 } from "./LeagueX3";
