/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace LeagueX3 {
  export type LeagueDataStruct = {
    ipfsLink: PromiseOrValue<string>;
    squadLimit: PromiseOrValue<BigNumberish>;
  };

  export type LeagueDataStructOutput = [string, number] & {
    ipfsLink: string;
    squadLimit: number;
  };

  export type UserLeagueDataStruct = {
    leagueDataLink: PromiseOrValue<string>;
    squads: PromiseOrValue<string>;
  };

  export type UserLeagueDataStructOutput = [string, string] & {
    leagueDataLink: string;
    squads: string;
  };
}

export interface LeagueX3Interface extends utils.Interface {
  functions: {
    "CreateUpdateLeague(string,string,uint16)": FunctionFragment;
    "GetLeagues(string)": FunctionFragment;
    "get_all_user_participation(address)": FunctionFragment;
    "get_user_league_participation(address,string)": FunctionFragment;
    "user_participate(address,string,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CreateUpdateLeague"
      | "GetLeagues"
      | "get_all_user_participation"
      | "get_user_league_participation"
      | "user_participate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CreateUpdateLeague",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "GetLeagues",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "get_all_user_participation",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "get_user_league_participation",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "user_participate",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "CreateUpdateLeague",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "GetLeagues", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "get_all_user_participation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_user_league_participation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "user_participate",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LeagueX3 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LeagueX3Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CreateUpdateLeague(
      matchCid: PromiseOrValue<string>,
      leagueIpfsLink: PromiseOrValue<string>,
      sLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    GetLeagues(
      matchCid: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[LeagueX3.LeagueDataStructOutput[]]>;

    get_all_user_participation(
      user_addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, LeagueX3.UserLeagueDataStructOutput[]]>;

    get_user_league_participation(
      user_addr: PromiseOrValue<string>,
      leagueLink: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, LeagueX3.UserLeagueDataStructOutput] & {
        u_addr: string;
        u_league: LeagueX3.UserLeagueDataStructOutput;
      }
    >;

    user_participate(
      user_addr: PromiseOrValue<string>,
      leagueLink: PromiseOrValue<string>,
      squadLink: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  CreateUpdateLeague(
    matchCid: PromiseOrValue<string>,
    leagueIpfsLink: PromiseOrValue<string>,
    sLimit: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  GetLeagues(
    matchCid: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<LeagueX3.LeagueDataStructOutput[]>;

  get_all_user_participation(
    user_addr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[string, LeagueX3.UserLeagueDataStructOutput[]]>;

  get_user_league_participation(
    user_addr: PromiseOrValue<string>,
    leagueLink: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, LeagueX3.UserLeagueDataStructOutput] & {
      u_addr: string;
      u_league: LeagueX3.UserLeagueDataStructOutput;
    }
  >;

  user_participate(
    user_addr: PromiseOrValue<string>,
    leagueLink: PromiseOrValue<string>,
    squadLink: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    CreateUpdateLeague(
      matchCid: PromiseOrValue<string>,
      leagueIpfsLink: PromiseOrValue<string>,
      sLimit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, number]>;

    GetLeagues(
      matchCid: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<LeagueX3.LeagueDataStructOutput[]>;

    get_all_user_participation(
      user_addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, LeagueX3.UserLeagueDataStructOutput[]]>;

    get_user_league_participation(
      user_addr: PromiseOrValue<string>,
      leagueLink: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, LeagueX3.UserLeagueDataStructOutput] & {
        u_addr: string;
        u_league: LeagueX3.UserLeagueDataStructOutput;
      }
    >;

    user_participate(
      user_addr: PromiseOrValue<string>,
      leagueLink: PromiseOrValue<string>,
      squadLink: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, LeagueX3.UserLeagueDataStructOutput]>;
  };

  filters: {};

  estimateGas: {
    CreateUpdateLeague(
      matchCid: PromiseOrValue<string>,
      leagueIpfsLink: PromiseOrValue<string>,
      sLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    GetLeagues(
      matchCid: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    get_all_user_participation(
      user_addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    get_user_league_participation(
      user_addr: PromiseOrValue<string>,
      leagueLink: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    user_participate(
      user_addr: PromiseOrValue<string>,
      leagueLink: PromiseOrValue<string>,
      squadLink: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CreateUpdateLeague(
      matchCid: PromiseOrValue<string>,
      leagueIpfsLink: PromiseOrValue<string>,
      sLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    GetLeagues(
      matchCid: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    get_all_user_participation(
      user_addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    get_user_league_participation(
      user_addr: PromiseOrValue<string>,
      leagueLink: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    user_participate(
      user_addr: PromiseOrValue<string>,
      leagueLink: PromiseOrValue<string>,
      squadLink: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
